Question1.
Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?
Ans.
Purpose of NumPy
NumPy is an open source library which provides support for scientific computing in Python. The primary objective of NumPy is to provide efficient and high performance operation on large, multi-dimensional arrays and matrices. The purpose behind its use is as follows:
•	Efficient numerical computations: NumPy offers a vast array of mathematical functions that operate directly on entire arrays, eliminating the need for slow Python loops.
•	Large dataset manipulation: NumPy can handle large amounts of data efficiently, making it ideal for tasks like image and signal processing.
•	Linear algebra operations: NumPy provides robust support for matrix operations, essential for various scientific and engineering applications.
Advantages of NumPy
•	Speed: NumPy is significantly faster than Python's built-in lists.
•	Memory efficiency: NumPy arrays are compact, storing data in contiguous memory blocks, reducing memory footprint.
•	Broadcasting: NumPy's broadcasting feature simplifies operations between arrays of different shapes.
•	Extensive functionality: It offers a rich set of mathematical functions, linear algebra routines, and random number generation capabilities.
•	Integration: NumPy seamlessly integrates with other scientific Python libraries like SciPy, Pandas, and Matplotlib.
Enhancing Python's Numerical Capabilities by
•	Providing efficient array objects: NumPy's  ndarray is the cornerstone, offering a fast and flexible way to store and manipulate numerical data.
•	Vectorization: NumPy allows you to perform operations on entire arrays at once, avoiding slow Python loops.
•	Linear algebra support: It provides essential linear algebra functions, making it suitable for tasks like solving linear equations, eigenvalue problems, and matrix decompositions.
•	Broadcasting: This feature enables operations between arrays of different shapes, simplifying complex calculations.
•	Integration with other libraries: NumPy serves as the foundation for many other scientific Python libraries, extending its capabilities even further.


2. Question:
Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?
Answer:
np.mean() vs np.average() functions in NumPy
np.mean()
•	Calculates the arithmetic mean of an array or along a specified axis.
•	Primarily used for simple average calculations.
•	Offers parameters like axis, dtype, out, and keepdims for customization.

np.average()
•	More versatile function that can compute both arithmetic and weighted means.  
•	Provides the weights parameter to calculate weighted averages.
•	Generally slower than np.mean() due to additional computations for weighted averages.

When we can use np.mean() and np.average()
•	np.mean():
o	When we need a simple arithmetic mean.
o	When performance is critical and weighted averages are not required.
•	np.average():
o	When we need to calculate a weighted average.
o	When flexibility is important and we might need to use other features of np.average(), such as handling masked arrays.


Question 3:
Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

Answer:
NumPy provides several methods to reverse the order of elements in an array along different axes. The methods for reversing NumPy Arrays along different axes are explained below.



In [ ]:
# Reversing a 1D Array
# Method 1: Slicing

import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
rev_arr = arr1[::-1]
print("Reversing a 1D Array using slicing ")
print(rev_arr)

# Method 2: np.flip()
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
rev_arr = np.flip(arr1)
print("Reversing a 1D Array using flip ")
print(rev_arr)

# Reversing a 2D Array
# Method 1: np.flip() with axis
# Reversing rows (axis=0):
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
rev_arr = np.flip(arr, axis=0)
print("Reversing a 2D Array using flip ")
print(rev_arr)

# Reversing columns (axis=1):
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
rev_arr = np.flip(arr, axis=1)
print("Reversing a 2D Array column using flip ")
print(rev_arr)

# Method 2: Slicing with multiple indices
#	Reversing rows:
rev_arr = arr[::-1, :]
print("Reversing rows using slicing with multriple indices ")
print(rev_arr)

# Reversing columns:
rev_arr = arr[:, ::-1]
print("Reversing columns  using slicing with multiple indices ")
print(rev_arr)



Reversing a 1D Array using slicing 
[5 4 3 2 1]
Reversing a 1D Array using flip 
[5 4 3 2 1]
Reversing a 2D Array using flip 
[[7 8 9]
 [4 5 6]
 [1 2 3]]
Reversing a 2D Array column using flip 
[[3 2 1]
 [6 5 4]
 [9 8 7]]
Reversing rows using slicing with multriple indices 
[[7 8 9]
 [4 5 6]
 [1 2 3]]
Reversing columns  using slicing with multiple indices 
[[3 2 1]
 [6 5 4]
 [9 8 7]]


Question 4.
How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

Answer:
Using the dtype attribute we can determine the data type of elements in a NumPy array.


In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3, 4])
print(arr1.dtype)


int64


Importance of Data Types in NumPy

Data types are crucial for memory management and performance optimization in NumPy. Let’s explain each, one after another

In Memory Management
•	Efficient storage: NumPy allocates memory based on the data type. For example, an int8 array will occupy less memory than an int64 array for the same number of elements.
•	Data consistency: Ensuring all elements have the same data type maintains data integrity and prevents unexpected behaviour.

In Performance Optimisation
•	Optimized operations: NumPy performs operations on entire arrays at once, and the data type significantly influences the speed of these operations. Using appropriate data types can lead to substantial performance gains.
•	Memory access patterns: NumPy is optimized for contiguous memory access. Correct data types help maintain this contiguity, improving performance.
•	Numerical precision: Different data types offer varying levels of precision. Choosing the right data type ensures accurate computations


Question 5.
Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

Answer.
ndarrays are the fundamental data structures in NumPy. They represent multidimensional arrays of homogeneous data types. This means that all elements in an ndarray must be of the same data type.

The Key features of ndarrays are as follows:

•	Multidimensional: ndarrays can represent data in any number of dimensions, from one-dimensional vectors to higher-dimensional matrices and tensors.
•	Homogeneous data types: All elements in an ndarray must have the same data type, which improves performance and memory efficiency.
•	Efficient operations: NumPy provides optimized functions for performing arithmetic, logical, and mathematical operations on entire arrays, leading to significant speedups compared to Python lists.
•	Broadcasting: NumPy supports broadcasting, which allows operations between arrays of different shapes under certain conditions.
•	Indexing and slicing: Powerful indexing and slicing capabilities for accessing and manipulating array elements.
•	Vectorization: Many operations can be performed element-wise without explicit loops, improving performance.

Differences between ndarrays and Python lists
•	Data types: ndarrays are homogeneous, while Python lists can contain elements of different data types.
•	Performance: ndarrays are significantly faster for numerical computations due to their underlying implementation and optimized operations.
•	Memory efficiency: ndarrays are generally more memory-efficient than Python lists.
•	Syntax: ndarrays provide a more concise syntax for many operations.
•	Functionality: ndarrays offer a rich set of mathematical functions and operations not available in Python lists.


Question 6.
Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

Answer:

Python lists and NumPy arrays have different strengths and weaknesses depending on the task to perform. NumPy arrays are designed specifically for numerical computations and are much faster than Python lists. They are also more memory-efficient than lists, as they require less memory to store the same amount of data. NumPy arrays have a fixed size and a specific data type, which makes them more suitable for numerical computations on large datasets.
While working with numerical data and need to perform operations like element-wise arithmetic operations, linear algebra operations, statistical operations, etc., NumPy arrays are typically more powerful and advantageous than Python lists due to their efficiency and optimized implementations.
Python lists are flexible and can hold different types of data, and they can be resized dynamically. Lists are useful for small to medium-sized datasets, especially when the data is heterogeneous (i.e., containing different types of data). However, they are not optimized for numerical computations and are slower than NumPy arrays.

Question 7.
Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

Answer:  

Comparison of vstack() and hstack() function in NumPy

vstack() function is used to stack the sequence of input arrays vertically to make a single array. Whereas, hstack() function is used to stack the sequence of input arrays horizontally (i.e. column wise) to make a single array.
vstack() is commonly used to concatenate arrays row-wise and all arrays must have the same shape along all but the first axis. But hstack() is useful for concatenating arrays with the same shape along all but the second axis, particularly when combining arrays of different shapes along the column-wise axis.


In [ ]:
# Example of vstack()
import numpy as np

x = np.array([[10, 20], [30, 40]])
y = np.array([[50, 60], [70, 80]])

z = np.vstack((x, y))
print("joining arrays vetrically")
print(z, "\n")

#EXample of hstack()
import numpy as np

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

z = np.hstack((x, y))
print("joining arrays horizontally")
print(z)


joining arrays vetrically
[[10 20]
 [30 40]
 [50 60]
 [70 80]] 

joining arrays horizontally
[[1 2 5 6]
 [3 4 7 8]]


Question 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.  

Answer.
Difference between fliplr() and flipud() in NumPy
•	fliplr() function is used to flip array in the left/right direction. But	flipud() function is used to flip a given array in the up/down direction.
•	fliplr() function flip the entries in each row in the left/right direction. Columns are preserved, but appear in a different order than before. Whereas flipud() flip the entries in each column in the up/down direction. Rows are preserved, but appear in a different order than before.
•	fliplr() function is particularly useful for image processing tasks such as flipping an image horizontally. But flipud() function is particularly useful in image processing tasks where flipping an image vertically is required, or in tasks where the order of rows in an array needs to be reversed.

Effects on different array dimensions:

In 1D Array:
•	Both fliplr() and flipud() will reverse the order of elements in the array.

In 2D Array:
•	fliplr() reverses the order of columns.
•	flipud() reverses the order of rows.

Higher-dimensional arrays:
•	Both functions operate on the specified axis. For example, in a 3D array, fliplr() would reverse the order of elements along the last axis of each 2D slice.



In [ ]:
# Example of fliplr() and flipud()

import numpy as np
# Create a 2D array
arr = np.array([[10, 20, 30],
               [40, 50, 60],
               [70, 80, 90]])
print(arr, "\n")
flipped_lr = np.fliplr(arr)
print("Flipping the array horizontally")
print(flipped_lr, "\n")

# Flipping vertically
flipped_ud = np.flipud(arr)
print("Flipping the array vertically")
print(flipped_ud)


[[10 20 30]
 [40 50 60]
 [70 80 90]] 

Flipping the array horizontally
[[30 20 10]
 [60 50 40]
 [90 80 70]] 

Flipping the array vertically
[[70 80 90]
 [40 50 60]
 [10 20 30]]


Question 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?  

Answer:

array_split is a NumPy function used to divide an array into multiple sub-arrays along a specified axis. Unlike its counterpart, split, array_split allows for uneven splitting of the array. This makes it more versatile for various data handling scenarios.
How it Works:
1.	Specifies the number of splits: You define the number of sub-arrays you want to create.
2.	Distributes elements: The function attempts to divide the array into equal-sized sub-arrays.
3.	Handles uneven splits: If the array cannot be evenly divided, the extra elements are distributed to the later sub-arrays.


In [ ]:
# Example of array split

import numpy as np
arr = np.arange(11)

# Split into 3 sub-arrays
split_arr = np.array_split(arr, 3)
print(split_arr)
#output  : [array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10])]
# Here we can see, the last sub-array has one extra element because the array length (11) is not evenly divisible by the number of splits (3).

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10])]


Question 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

Answer:
Vectorization in NumPy refers to the process of applying operations to entire arrays (or vectors) without using explicit loops. It only uses the pre-defined inbuilt functions like the sum function etc., and mathematical operations like "+", "-", "/" etc. for performing operations in Numpy arrays.

Broadcasting is a powerful mechanism that allows NumPy to perform operations on arrays of different shapes. It involves stretching or repeating the smaller array to match the shape of the larger array before performing the operation.

Contribution of Vectorization and Broadcasting in Efficient Array Operations

•	Vectorization:
o	Eliminates the overhead of Python loops, leading to significant speedups.
o	Allows for concise and readable code.
o	Takes advantage of NumPy's optimized underlying implementations.

•	Broadcasting:
o	Enables operations between arrays of different shapes without explicit reshaping.
o	Simplifies code and reduces the need for manual array manipulation.
o	Contributes to efficient memory usage by avoiding unnecessary data copies.

By combining vectorization and broadcasting, NumPy provides a powerful and efficient way to perform complex numerical computations on large datasets. These features are essential for scientific computing, data analysis, and machine learning applications.


In [ ]:
# Example of vectorization
import numpy as np
arr=np.arange(1,20,4)
arr1=np.arange(1,10,2)
print("Array arr:",arr)
print("Array arr1:",arr1)
print()
arr2=(arr+arr1)
print("The sum of elements of arr and arr1 using vectorization: ",arr2, "\n")

# Example of broadcasting
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([[10],[20],[30]])

arr3 = arr1 +arr2
print("The sum of elements of arr1 and arr2 using broadcasting:","\n",arr3)

Array arr: [ 1  5  9 13 17]
Array arr1: [1 3 5 7 9]

The sum of elements of arr and arr1 using vectorization:  [ 2  8 14 20 26] 

The sum of elements of arr1 and arr2 using broadcasting: 
 [[11 12 13]
 [21 22 23]
 [31 32 33]]


**PRACTICAL QUESTIONS **
Question 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns

In [ ]:
import numpy as np
arr1= np.random.randint(1, 101, size = (3,3))

# interchange its rows and columns
transpose_array = np.transpose(arr1)

print("The original array is:","\n", arr1)
print()
print("After transposing the array", "\n", transpose_array)

The original array is: 
 [[72 52 68]
 [16 17 60]
 [21 40 91]]

After transposing the array 
 [[72 16 21]
 [52 17 40]
 [68 60 91]]


Quetion 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [ ]:
import numpy as np
arr1 = np.random.randint(1, 100, size =(10))
print(arr1)

#Reshape it into 2X5 array
arr2 = np.reshape(arr1, (2,5))
print()
print("Reshaping the array in to 2X5 array")
print(arr2)

#Reshaping it into 5X2 array
arr3 = np.reshape(arr1, (5,2))
print()
print("Reshaping the array in to 5X2 array")
print(arr3)


[ 9  1 53 64 43 67 14 92 85 96]

Reshaping the array in to 2X5 array
[[ 9  1 53 64 43]
 [67 14 92 85 96]]

Reshaping the array in to 5X2 array
[[ 9  1]
 [53 64]
 [43 67]
 [14 92]
 [85 96]]


Question 3.  Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.


In [ ]:
import numpy as np
arr1 = np.random.rand(4,4)
print("The original array is:","\n", arr1)
print()

#Adding a border of zeros around 4X4 array and resulting to 6X6 array
arr2 = np.pad(arr1, pad_width=1, mode = 'constant', constant_values= 0 )
print("Adding a border of zeros around 4X4 array and resulting to 6X6 array", "\n")
print(arr2)



The original array is: 
 [[0.61321334 0.24552266 0.51081273 0.18391143]
 [0.87677346 0.88005321 0.43513795 0.0798146 ]
 [0.50456841 0.23694895 0.97646264 0.54529522]
 [0.02467338 0.47608245 0.23003666 0.50454398]]

Adding a border of zeros around 4X4 array and resulting to 6X6 array 

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.61321334 0.24552266 0.51081273 0.18391143 0.        ]
 [0.         0.87677346 0.88005321 0.43513795 0.0798146  0.        ]
 [0.         0.50456841 0.23694895 0.97646264 0.54529522 0.        ]
 [0.         0.02467338 0.47608245 0.23003666 0.50454398 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


Question 4.  Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [ ]:
import numpy as np
arr1 = np.arange(10, 61, 5)
print(arr1)


[10 15 20 25 30 35 40 45 50 55 60]


Question 5.  Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [ ]:
import numpy as np
arr1 = np.array(['python', 'numpy', 'pandas'])
print("Array of strings", arr1, "\n")
print("String to uppercase")
array_to_upper= np.char.upper(arr1)
print(array_to_upper, "\n")
print("String to Lowercase")
array_to_lower= np.char.lower(arr1)
print(array_to_lower, "\n")
print("String to title")
array_to_title= np.char.title(arr1)
print(array_to_title)



Array of strings ['python' 'numpy' 'pandas'] 

String to uppercase
['PYTHON' 'NUMPY' 'PANDAS'] 

String to Lowercase
['python' 'numpy' 'pandas'] 

String to title
['Python' 'Numpy' 'Pandas']


Question 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [ ]:
import numpy as np
arr = np.array(['Learning','the','course','of','data','analytics'])
print("Array of words", arr, "\n")
#  Inserting a space between each character of every word in the array
arr1 = np.char.join(' ', arr)
print("After inserting a space between each character of every word in the array", "\n")
print(arr1)


Array of words ['Learning' 'the' 'course' 'of' 'data' 'analytics'] 

After inserting a space between each character of every word in the array 

['L e a r n i n g' 't h e' 'c o u r s e' 'o f' 'd a t a'
 'a n a l y t i c s']


Question 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [ ]:
import numpy as np
arr1 = np.array([[10, 20, 30], [40,50, 60]])
arr2 = np.array([[2,4,6], [8,10,12]])
#Element wise addition, subtraction, multiplication, and division

addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2

print("Element wise addition", "\n", addition)
print()
print("Element wise subtraction", "\n", subtraction)
print()
print("Element wise multiplication", "\n", multiplication)
print()
print("Element wise division", "\n", division)


Element wise addition 
 [[12 24 36]
 [48 60 72]]

Element wise subtraction 
 [[ 8 16 24]
 [32 40 48]]

Element wise multiplication 
 [[ 20  80 180]
 [320 500 720]]

Element wise division 
 [[5. 5. 5.]
 [5. 5. 5.]]


 Question 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [ ]:
import numpy as np
identical_matrix = np.identity(5)
print("5X5 identity matrix")
print(identical_matrix, "\n")

diagonal_elements = np.diagonal(identical_matrix)
print("After extracting its diagonal elements")
print(diagonal_elements, "\n")

5X5 identity matrix
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

After extracting its diagonal elements
[1. 1. 1. 1. 1.] 



Question 9.  Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array

In [3]:
import numpy as np
#define a function to check prime
def is_prime(n) :
    if n<=1:
      return False
    if n == 2:
      return True
    if n%2 == 0:
      return False
    for i in range(3, int(np.sqrt(n)+1, 2)):
      if n%i == 0:
        return False
    return True

arr = np.random.randint(0, 1001, 100)
print(arr)


[752 109 488 407 898 284 224 187 497 938 960  38 649 893 282 246 463 239
 215 317 421 442  96 415 524 981 672 957 432 287 920  68 243 786 233 963
 468 928 870 989 498 835 700 461 408 131 702 297 243 247 367 980 791 955
  53 768 215 756 934 805 442 289 333 365  89 877  49 826 221 125 859  42
 838  32 434 676 332 386 907 341 527 730 819 772 483 925  86 757 906 348
 613 850 579 442  29 863 460  11 117  12]


Question 10.  Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.


In [13]:
# Assuming a 30-day month
daily_temperatures = np.random.randint(60, 90, 30)

# Calculate the number of elements needed to pad
num_pad = (7 - (daily_temperatures.size % 7)) % 7

# Pad the array with zeros
padded_temperatures = np.pad(daily_temperatures, (0, num_pad), 'constant', constant_values=0)

# Reshape the padded array
reshaped_temperatures = padded_temperatures.reshape(-1, 7)

# Calculate weekly averages
weekly_averages = np.mean(reshaped_temperatures, axis=1)

print("Daily Temperatures:")
print(daily_temperatures)
print("\nWeekly Averages:")
print(weekly_averages)

Daily Temperatures:
[64 63 81 87 86 73 75 64 80 69 61 74 71 72 71 71 67 73 79 66 84 64 61 77
 64 82 61 79 88 68]

Weekly Averages:
[75.57142857 70.14285714 73.         69.71428571 22.28571429]
